version: "3.1"

services:
    apache:
        image: httpd:latest
        ports:
            - '8080:80'
        volumes:
            - .:/usr/local/apache2/htdocs
        depends_on:
            - php

    php:
        build: './docker/php'
        volumes:
            - .:/usr/local/apache2/htdocs

    postgres:
        image: postgres:latest
        ports:
            - '5432:5432'

