version: "3.1"

services:
    nginx:
        image: nginx:latest
        ports:
            - '8000:80'
        volumes:
            - .:/srv/forteroche

    php:
        build: './docker/php'
        volumes:
            - .:/usr/local/apache2/htdocs

    postgres:
        image: postgres:latest
        ports:
            - '5432:5432'

